# Generated by Django 4.1.7 on 2023-03-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_documento", models.CharField(max_length=25)),
                ("documento", models.CharField(max_length=10)),
                ("nombres", models.CharField(max_length=25)),
                ("apellidos", models.CharField(max_length=25)),
                ("genero", models.CharField(max_length=7)),
                ("fecha_nacimiento", models.DateField()),
                ("telefono", models.CharField(max_length=10)),
                ("correo", models.CharField(max_length=70)),
                ("direccion", models.CharField(max_length=100)),
                ("estado", models.BooleanField()),
            ],
            options={
                "db_table": "clientes",
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_completo", models.CharField(max_length=65)),
                ("correo", models.CharField(max_length=70)),
                ("contrasena", models.CharField(max_length=15)),
                ("estado", models.BooleanField()),
            ],
            options={
                "db_table": "usuarios",
            },
        ),
        migrations.CreateModel(
            name="Mascotas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_mascota", models.CharField(max_length=6)),
                ("nombre", models.CharField(max_length=35)),
                ("sexo", models.CharField(max_length=7)),
                ("fecha_nacimiento", models.DateField()),
                ("raza", models.CharField(max_length=25)),
                ("estado", models.BooleanField()),
                (
                    "id_cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Sistema_Veterinario.clientes",
                    ),
                ),
            ],
            options={
                "db_table": "mascotas",
            },
        ),
        migrations.CreateModel(
            name="Agendar_Cita",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("estado", models.BooleanField()),
                (
                    "id_mascota",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Sistema_Veterinario.mascotas",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Sistema_Veterinario.usuarios",
                    ),
                ),
            ],
            options={
                "db_table": "agendar_cita",
            },
        ),
    ]
